schema = {
'group1' : ['DIFERENCA_50C',],
    
'group2' : ['COD_CLASSE_BONUS',],
    
'group3' : ['PREM_EMITIDO_ATU',],
    
'group4' : ['COD_TIPO_RENOV',],
    
'group5' : ['LMR_CASCO',],
    
'group6' : ['IDC_SEXO_CONDUTOR_FINAL',],
    
'group7' : ['PREM_EMITIDO_ANUAL',],
    
'group8' : ['SOMA_PERIODO',],
    
'group9' : ['QTD_IDADE_VEICULO',],
    
'group10' : ['FIDELIZACAO',],
    
'group11' :['SIG_UF',],
    
'group12' :['F_CAPITAL',],
    
'group13' :['SP_RENOV',
'RAZAO_C',
'IDC_ESTADO_CIVIL',
'IDC_PROCED_VEICULO',],
    
'group14' :['SP_INICIAL',
'TX_COMER_RENOV',
'IDC_18_24ANOS_FINAL',
'CATEGORIA',],
    
'group15' :['pct_perda_corretor_lag2',
'MUDANCA_RISCO',
'FLG_VEICULO_NOVO',
'COD_PORTE_VEICULO',],
    
'group16' :['pct_perda_corretor_lag3',
'COD_FAMILIA_VEICULO',
'QTD_SIN_TOTAL',
'COD_SEGMENTO_VEICULO',],
    
'group17' :['pct_perda_corretor_lag4',
'COD_REGIAO_POLITICA',
'FLG_PARCERIA',
'IDC_AVAL_RISCO',],
    
'group18' :['pct_perda_corretor_lag5',
'IDADE_SEGURADO_FINAL',
'QTD_SIN_GAR',
'COD_PROD',],
    
'group19' :['COD_TIPO_VEICULO',
'DSC_ABREV_SEGRA',
'QTD_SIN_PP',],
#'percent_gar_contr',],
    
'group20' :['COD_USO_VEICULO',
'QTD_SIN_RCF',
'sow_lag2',],

'group21' :['GANHO_SUM_reg_cat',],
'group22' :['PERDA_SUM_reg_cat',],
'group23' :['GANHO_SUM_reg',],
'group24' :['PERDA_SUM_reg',],
'group25' :['GANHO_SUM_LAG_3_reg',],
'group26' :['PERDA_SUM_LAG_3_reg',],
'group27' :['GANHO_SUM_LAG_6_reg',],
'group28' :['PERDA_SUM_LAG_6_reg',],
    
    
'group29' :['TX_COMERCIAL_ALLIANZ',
'TX_COMERCIAL_AZUL',
'TX_COMERCIAL_BRADESCO',
'TX_COMERCIAL_HDI',
'TX_COMERCIAL_LIBERTY',
'TX_COMERCIAL_MAPFRE',
'TX_COMERCIAL_PORTO',
'TX_COMERCIAL_TOKIO',],
    
'group30' :['TX_COMERCIAL_ALLIANZ_LAG_1',
'TX_COMERCIAL_AZUL_LAG_1',
'TX_COMERCIAL_BRADESCO_LAG_1',
'TX_COMERCIAL_HDI_LAG_1',
'TX_COMERCIAL_LIBERTY_LAG_1',
'TX_COMERCIAL_MAPFRE_LAG_1',
'TX_COMERCIAL_PORTO_LAG_1',
'TX_COMERCIAL_TOKIO_LAG_1',],
    
'group31' :['TX_COMERCIAL_ALLIANZ_LAG_2',
'TX_COMERCIAL_AZUL_LAG_2',
'TX_COMERCIAL_BRADESCO_LAG_2',
'TX_COMERCIAL_HDI_LAG_2',
'TX_COMERCIAL_LIBERTY_LAG_2',
'TX_COMERCIAL_MAPFRE_LAG_2',
'TX_COMERCIAL_PORTO_LAG_2',
'TX_COMERCIAL_TOKIO_LAG_2',],
    
'group32' :['TX_COMERCIAL_ALLIANZ_LAG_3',
'TX_COMERCIAL_AZUL_LAG_3',
'TX_COMERCIAL_BRADESCO_LAG_3',
'TX_COMERCIAL_HDI_LAG_3',
'TX_COMERCIAL_LIBERTY_LAG_3',
'TX_COMERCIAL_MAPFRE_LAG_3',
'TX_COMERCIAL_PORTO_LAG_3',
'TX_COMERCIAL_TOKIO_LAG_3',],
    
'group33' :['TX_COMERCIAL_ALLIANZ_LAG_4',
'TX_COMERCIAL_AZUL_LAG_4',
'TX_COMERCIAL_BRADESCO_LAG_4',
'TX_COMERCIAL_HDI_LAG_4',
'TX_COMERCIAL_LIBERTY_LAG_4',
'TX_COMERCIAL_MAPFRE_LAG_4',
'TX_COMERCIAL_PORTO_LAG_4',
'TX_COMERCIAL_TOKIO_LAG_4',],
    
'group34' :['TX_COMERCIAL_ALLIANZ_LAG_5',
'TX_COMERCIAL_AZUL_LAG_5',
'TX_COMERCIAL_BRADESCO_LAG_5',
'TX_COMERCIAL_HDI_LAG_5',
'TX_COMERCIAL_LIBERTY_LAG_5',
'TX_COMERCIAL_MAPFRE_LAG_5',
'TX_COMERCIAL_PORTO_LAG_5',
'TX_COMERCIAL_TOKIO_LAG_5',],
    
'group35' :['TX_COMERCIAL_ALLIANZ_LAG_6',
'TX_COMERCIAL_AZUL_LAG_6',
'TX_COMERCIAL_BRADESCO_LAG_6',
'TX_COMERCIAL_HDI_LAG_6',
'TX_COMERCIAL_LIBERTY_LAG_6',
'TX_COMERCIAL_MAPFRE_LAG_6',
'TX_COMERCIAL_PORTO_LAG_6',
'TX_COMERCIAL_TOKIO_LAG_6',],

'group36' : ['SCORE_PREMIO',],
'group37' : ['SCORE_COMISSAO',],
'group38' : ['SCORE_RISCO',],
'group39' : ['SCORE_TEMPORAL',],
'group40' : ['SCORE_CAPTACAO_RNV_SAS',],
'group41' : ['SCORE_CAPTACAO_TOTAL',],
'group42' : ['SCORE_TAMANHO',],
'group43' : ['SCORE_CAPTACAO_VN',],
'group44' : ['SCORE_MARGEM',],
'group45' : ['IC',],
'group46' : ['IC_LAG_1',],
'group47' : ['IC_LAG_2',],
'group48' : ['IC_LAG_3',]
}
