################################################
## INPUT TABLE 

table_name: sas-auto-marketprice-analytics.MKT_PRICING.MKT_PRICING_RENOV_201807_20191023_UPDFEAT
destination_table: sas-auto-marketprice-analytics.MKT_PRICING.MKT_PRICING_RENOV_201807_20191023_UPDFEAT_MODEL

################################################
## OPERATIONS

operations:
    - filter_table:
        where: WHERE  COD_CAT_TARIFA_BAS in (10, 11, 14, 15, 20, 21)
    - scaler_min_max:
        lower_bound_percent: 1
        upper_bound_percent: 95
        features: 
            - VAL_PR_ANUAL_LIQUIDO
            - VAL_PR_ANUAL_LIQUIDO_RENOV
            - VPR_AJ_JUD_TEND_ENV
            - RAZAO_C
            - TX_COMER_RENOV
            - FAT_TT_GLM_ARRED
            - SP_INICIAL
            - SP_RENOV
            - QTD_IDADE_VEICULO
            - VAL_LMR_CASCO
            - VAL_LMR_CASCO_RENOV
            - PCT_PERDA_CORRETOR_LAG1
            - PCT_PERDA_CORRETOR_LAG2
            - PCT_PERDA_CORRETOR_LAG3
            - PCT_PERDA_CORRETOR_LAG4
            - PCT_PERDA_CORRETOR_LAG5
            - SOW_LAG1
            - SOW_LAG2
            - SOW_LAG3
            - SOW_LAG4
            - SOW_LAG5
            - GANHO_SUM_reg
            - PERDA_SUM_reg
            - GANHO_SUM_LAG_1_reg
            - PERDA_SUM_LAG_1_reg
            - GANHO_SUM_LAG_2_reg
            - PERDA_SUM_LAG_2_reg
            - GANHO_SUM_LAG_3_reg
            - PERDA_SUM_LAG_3_reg
            - GANHO_SUM_LAG_4_reg
            - PERDA_SUM_LAG_4_reg
            - GANHO_SUM_LAG_5_reg
            - PERDA_SUM_LAG_5_reg
            - GANHO_SUM_LAG_6_reg
            - PERDA_SUM_LAG_6_reg
            - GANHO_SUM_reg_cat
            - PERDA_SUM_reg_cat
            - GANHO_SUM_LAG_1_reg_cat
            - PERDA_SUM_LAG_1_reg_cat
            - GANHO_SUM_LAG_2_reg_cat
            - PERDA_SUM_LAG_2_reg_cat
            - GANHO_SUM_LAG_3_reg_cat
            - PERDA_SUM_LAG_3_reg_cat
            - GANHO_SUM_LAG_4_reg_cat
            - PERDA_SUM_LAG_4_reg_cat
            - GANHO_SUM_LAG_5_reg_cat
            - PERDA_SUM_LAG_5_reg_cat
            - GANHO_SUM_LAG_6_reg_cat
            - PERDA_SUM_LAG_6_reg_cat
            - TX_COMERCIAL_ALLIANZ
            - TX_COMERCIAL_AZUL
            - TX_COMERCIAL_BRADESCO
            - TX_COMERCIAL_HDI
            - TX_COMERCIAL_LIBERTY
            - TX_COMERCIAL_MAPFRE
            - TX_COMERCIAL_PORTO
            - TX_COMERCIAL_TOKIO
            - TX_COMERCIAL_ALLIANZ_LAG_1
            - TX_COMERCIAL_AZUL_LAG_1
            - TX_COMERCIAL_BRADESCO_LAG_1
            - TX_COMERCIAL_HDI_LAG_1
            - TX_COMERCIAL_LIBERTY_LAG_1
            - TX_COMERCIAL_MAPFRE_LAG_1
            - TX_COMERCIAL_PORTO_LAG_1
            - TX_COMERCIAL_TOKIO_LAG_1
            - TX_COMERCIAL_ALLIANZ_LAG_2
            - TX_COMERCIAL_AZUL_LAG_2
            - TX_COMERCIAL_BRADESCO_LAG_2
            - TX_COMERCIAL_HDI_LAG_2
            - TX_COMERCIAL_LIBERTY_LAG_2
            - TX_COMERCIAL_MAPFRE_LAG_2
            - TX_COMERCIAL_PORTO_LAG_2
            - TX_COMERCIAL_TOKIO_LAG_2
            - TX_COMERCIAL_ALLIANZ_LAG_3
            - TX_COMERCIAL_AZUL_LAG_3
            - TX_COMERCIAL_BRADESCO_LAG_3
            - TX_COMERCIAL_HDI_LAG_3
            - TX_COMERCIAL_LIBERTY_LAG_3
            - TX_COMERCIAL_MAPFRE_LAG_3
            - TX_COMERCIAL_PORTO_LAG_3
            - TX_COMERCIAL_TOKIO_LAG_3
            - TX_COMERCIAL_ALLIANZ_LAG_4
            - TX_COMERCIAL_AZUL_LAG_4
            - TX_COMERCIAL_BRADESCO_LAG_4
            - TX_COMERCIAL_HDI_LAG_4
            - TX_COMERCIAL_LIBERTY_LAG_4
            - TX_COMERCIAL_MAPFRE_LAG_4
            - TX_COMERCIAL_PORTO_LAG_4
            - TX_COMERCIAL_TOKIO_LAG_4
            - TX_COMERCIAL_ALLIANZ_LAG_5
            - TX_COMERCIAL_AZUL_LAG_5
            - TX_COMERCIAL_BRADESCO_LAG_5
            - TX_COMERCIAL_HDI_LAG_5
            - TX_COMERCIAL_LIBERTY_LAG_5
            - TX_COMERCIAL_MAPFRE_LAG_5
            - TX_COMERCIAL_PORTO_LAG_5
            - TX_COMERCIAL_TOKIO_LAG_5
            - TX_COMERCIAL_ALLIANZ_LAG_6
            - TX_COMERCIAL_AZUL_LAG_6
            - TX_COMERCIAL_BRADESCO_LAG_6
            - TX_COMERCIAL_HDI_LAG_6
            - TX_COMERCIAL_LIBERTY_LAG_6
            - TX_COMERCIAL_MAPFRE_LAG_6
            - TX_COMERCIAL_PORTO_LAG_6
            - TX_COMERCIAL_TOKIO_LAG_6
            - IC
            - IC_LAG_1
            - IC_LAG_2
            - IC_LAG_3
            - IC_LAG_4
            - IC_LAG_5
            - IC_LAG_6
            - SCORE_CAPTACAO_RNV_SAS
            - SCORE_CAPTACAO_VN
            - SCORE_RISCO
            - SCORE_TAMANHO
            - SCORE_PREMIO
            - SCORE_COMISSAO
            - SCORE_TEMPORAL
            - SCORE_CAPTACAO_TOTAL
            - COMIS
            - VAL_MARGEM
            - SOMA_PERIODO_EV
            - SOMA_PERIODO
            - QTD_IDADE_CONDUTOR_MODEL
            - DIFERENCA_50C
            - QTD_SIN_TOTAL
            - QTD_SIN_GAR
            - QTD_SIN_PP
            - QTD_SIN_RCF
            - SCORE_MARGEM
            - SCORE_CSPA
            - RENDA_CRP7

    - fill_missing_median:
        features: 
            - VAL_PR_ANUAL_LIQUIDO
            - VAL_PR_ANUAL_LIQUIDO_RENOV
            - VPR_AJ_JUD_TEND_ENV
            - RAZAO_C
            - TX_COMER_RENOV
            - FAT_TT_GLM_ARRED
            - SP_INICIAL
            - SP_RENOV
            - QTD_IDADE_VEICULO
            - VAL_LMR_CASCO
            - VAL_LMR_CASCO_RENOV
            - PCT_PERDA_CORRETOR_LAG1
            - PCT_PERDA_CORRETOR_LAG2
            - PCT_PERDA_CORRETOR_LAG3
            - PCT_PERDA_CORRETOR_LAG4
            - PCT_PERDA_CORRETOR_LAG5
            - SOW_LAG1
            - SOW_LAG2
            - SOW_LAG3
            - SOW_LAG4
            - SOW_LAG5
            - GANHO_SUM_reg
            - PERDA_SUM_reg
            - GANHO_SUM_LAG_1_reg
            - PERDA_SUM_LAG_1_reg
            - GANHO_SUM_LAG_2_reg
            - PERDA_SUM_LAG_2_reg
            - GANHO_SUM_LAG_3_reg
            - PERDA_SUM_LAG_3_reg
            - GANHO_SUM_LAG_4_reg
            - PERDA_SUM_LAG_4_reg
            - GANHO_SUM_LAG_5_reg
            - PERDA_SUM_LAG_5_reg
            - GANHO_SUM_LAG_6_reg
            - PERDA_SUM_LAG_6_reg
            - GANHO_SUM_reg_cat
            - PERDA_SUM_reg_cat
            - GANHO_SUM_LAG_1_reg_cat
            - PERDA_SUM_LAG_1_reg_cat
            - GANHO_SUM_LAG_2_reg_cat
            - PERDA_SUM_LAG_2_reg_cat
            - GANHO_SUM_LAG_3_reg_cat
            - PERDA_SUM_LAG_3_reg_cat
            - GANHO_SUM_LAG_4_reg_cat
            - PERDA_SUM_LAG_4_reg_cat
            - GANHO_SUM_LAG_5_reg_cat
            - PERDA_SUM_LAG_5_reg_cat
            - GANHO_SUM_LAG_6_reg_cat
            - PERDA_SUM_LAG_6_reg_cat
            - TX_COMERCIAL_ALLIANZ
            - TX_COMERCIAL_AZUL
            - TX_COMERCIAL_BRADESCO
            - TX_COMERCIAL_HDI
            - TX_COMERCIAL_LIBERTY
            - TX_COMERCIAL_MAPFRE
            - TX_COMERCIAL_PORTO
            - TX_COMERCIAL_TOKIO
            - TX_COMERCIAL_ALLIANZ_LAG_1
            - TX_COMERCIAL_AZUL_LAG_1
            - TX_COMERCIAL_BRADESCO_LAG_1
            - TX_COMERCIAL_HDI_LAG_1
            - TX_COMERCIAL_LIBERTY_LAG_1
            - TX_COMERCIAL_MAPFRE_LAG_1
            - TX_COMERCIAL_PORTO_LAG_1
            - TX_COMERCIAL_TOKIO_LAG_1
            - TX_COMERCIAL_ALLIANZ_LAG_2
            - TX_COMERCIAL_AZUL_LAG_2
            - TX_COMERCIAL_BRADESCO_LAG_2
            - TX_COMERCIAL_HDI_LAG_2
            - TX_COMERCIAL_LIBERTY_LAG_2
            - TX_COMERCIAL_MAPFRE_LAG_2
            - TX_COMERCIAL_PORTO_LAG_2
            - TX_COMERCIAL_TOKIO_LAG_2
            - TX_COMERCIAL_ALLIANZ_LAG_3
            - TX_COMERCIAL_AZUL_LAG_3
            - TX_COMERCIAL_BRADESCO_LAG_3
            - TX_COMERCIAL_HDI_LAG_3
            - TX_COMERCIAL_LIBERTY_LAG_3
            - TX_COMERCIAL_MAPFRE_LAG_3
            - TX_COMERCIAL_PORTO_LAG_3
            - TX_COMERCIAL_TOKIO_LAG_3
            - TX_COMERCIAL_ALLIANZ_LAG_4
            - TX_COMERCIAL_AZUL_LAG_4
            - TX_COMERCIAL_BRADESCO_LAG_4
            - TX_COMERCIAL_HDI_LAG_4
            - TX_COMERCIAL_LIBERTY_LAG_4
            - TX_COMERCIAL_MAPFRE_LAG_4
            - TX_COMERCIAL_PORTO_LAG_4
            - TX_COMERCIAL_TOKIO_LAG_4
            - TX_COMERCIAL_ALLIANZ_LAG_5
            - TX_COMERCIAL_AZUL_LAG_5
            - TX_COMERCIAL_BRADESCO_LAG_5
            - TX_COMERCIAL_HDI_LAG_5
            - TX_COMERCIAL_LIBERTY_LAG_5
            - TX_COMERCIAL_MAPFRE_LAG_5
            - TX_COMERCIAL_PORTO_LAG_5
            - TX_COMERCIAL_TOKIO_LAG_5
            - TX_COMERCIAL_ALLIANZ_LAG_6
            - TX_COMERCIAL_AZUL_LAG_6
            - TX_COMERCIAL_BRADESCO_LAG_6
            - TX_COMERCIAL_HDI_LAG_6
            - TX_COMERCIAL_LIBERTY_LAG_6
            - TX_COMERCIAL_MAPFRE_LAG_6
            - TX_COMERCIAL_PORTO_LAG_6
            - TX_COMERCIAL_TOKIO_LAG_6
            - IC
            - IC_LAG_1
            - IC_LAG_2
            - IC_LAG_3
            - IC_LAG_4
            - IC_LAG_5
            - IC_LAG_6
            - SCORE_CAPTACAO_RNV_SAS
            - SCORE_CAPTACAO_VN
            - SCORE_RISCO
            - SCORE_TAMANHO
            - SCORE_PREMIO
            - SCORE_COMISSAO
            - SCORE_TEMPORAL
            - SCORE_CAPTACAO_TOTAL
            - COMIS
            - VAL_MARGEM
            - SOMA_PERIODO_EV
            - SOMA_PERIODO
            - QTD_IDADE_CONDUTOR_MODEL
            - DIFERENCA_50C
            - QTD_SIN_TOTAL
            - QTD_SIN_GAR
            - QTD_SIN_PP
            - QTD_SIN_RCF
            - SCORE_MARGEM
            - SCORE_CSPA
            - RENDA_CRP7
            
            
    - fill_most_frequent:
        features:
            - COD_CLASSE_BONUS
            - COD_TIPO_RENOV
            - DSC_TIPO_RENOV
            - DSC_SEGRA_ANT
            - MUDANCA_RISCO
            - DSC_AVAL_RISCO
            - DSC_SEXO_CONDUTOR
            - IDC_ESTADO_CIVIL_CONDUTOR
            - FIDELIZACAO
            - DSC_RESID_JOVEM_PART
            - COD_ESTR_VENDA
            - COD_PROD
            - DSC_PROD
            - NME_REGIONAL_PRECO
            - SIG_UF_PRECO
            - SIG_UF_SPINT_PRECO
            - COD_REGIAO_RISCO
            - NME_REGIAO_RISCO
            - COD_REGIAO_POLITICA
            - NME_REGIAO_POLITICA
            - COD_USO_VEICULO
            - DSC_USO_VEICULO
            - COD_CAT_TARIFA_BAS
            - DSC_CAT_TARIFA_BAS
            - COD_TIPO_VEICULO
            - DSC_TIPO_VEICULO
            - COD_PORTE_VEICULO
            - DSC_PORTE_VEICULO
            - COD_SEGMENTO_VEICULO
            - DSC_SEGMENTO_VEICULO
            - SIG_FABRIC
            - DSC_PROCED_VEICULO
            - FLG_VEICULO_NOVO
            - COD_FAMILIA_VEICULO
            - DSC_FAMILIA_VEICULO
            - Grupo_Idade_Segurado
            - Grupo_RiscoFamilia
            - CAPTACAO_RNV_SAS
            - CAPTACAO_VN
            - RISCO
            - TAMANHO
            - PREMIO_LMR
            - COMISSAO_DESCONTO
            - TEMPORAL
            - FLAG_TAMANHO
            - CAPTACAO_TOTAL
            - MARGEM
            - CLASSIFICACAO
            - SIG_TIPO_DOC_COBR

            
        
    