/################################################
## STORAGE DIRECTORY 

base_dir: gs://marketprice/renov/bain/sp5/ds/
ds_name: flow_test
base_dir_predict: gs://marketprice/renov/bain/sp5/predict/
model_name: flow_test

run_dir: /data/
report_id: first_test

################################################
## BACKTEST PARAMS

initial_training_month: 1-7-2018
last_predicting_month:  31-7-2019 

save_experiment: False

################################################
## ELASTICITY PARAMS

elasticity_periods: 201908


################################################
## FEATURE PARAMS

original_params:
    date_col: DAT_FIM_VIGENCIA_GERAL
    target: QTD_PROP
    hash_col: key

params:  
    date_col: DATE
    target: TARGET
    model_output: PREDICTED

analysis_variables:  
    - KEY
    - COD_CAT_TARIFA_BAS
    - COD_TIPO_RENOV
    - NME_REGIONAL_PRECO
    - VAL_PR_ANUAL_LIQUIDO_RENOV
    - VAL_PR_ANUAL_LIQUIDO
    
elasticity_variables: TESTE

label: QTD_PROP

feature_label: all_features + label

vehicle_categ: 10, 11, 14, 15, 20, 21
dataset_filter: WHERE  COD_CAT_TARIFA_BAS in (10, 11, 14, 15, 20, 21)
table_name: sas-auto-marketprice-analytics.MKT_PRICING.MKT_PRICING_RENOV_201807_20191023_UPDFEAT_MODEL


################################################
## PIPELINE PARAMS

dataset_generator_params:
    all_features: 
        - FIDELIZACAO
        - VAL_LMR_CASCO
        - SCORE_CAPTACAO_VN
        - SCORE_CAPTACAO_TOTAL
        - VAL_PR_ANUAL_LIQUIDO_RENOV
        - PERDA_SUM_LAG_3_reg
        - GANHO_SUM_reg_cat
        - COD_CLASSE_BONUS
        - PCT_PERDA_CORRETOR_LAG3
        - COD_FAMILIA_VEICULO
        - FLG_VEICULO_NOVO
        - COD_PORTE_VEICULO
        - SP_INICIAL
        - IDC_ESTADO_CIVIL_CONDUTOR
        - IDC_PROCED_VEICULO
        - SIG_UF_PRECO
        - DSC_SEXO_CONDUTOR
        - VAL_PR_ANUAL_LIQUIDO
        
    tl: 1          # Train Lenght
    tl_mode: m
    ld: 1          # Lead Time
    ld_mode: m
    testl: 3       # Test Length
    testl_mode: m
    sl: 1         # Stride Length
    sl_mode: m
    
    method: gcp_bq

task_engineer_params:
    methods: 
        one_hot_mean_enc:
            small_categorical: 
               - IDC_AVAL_RISCO
               - MUDANCA_RISCO
               - COD_CLASSE_BONUS
               - COD_CAT_TARIFA_BAS
               - FLG_CAPITAL
               - NME_REGIONAL_PRECO
               - DSC_RESID_JOVEM_PART
               - COD_PORTE_VEICULO
               - FIDELIZACAO
               - COD_TIPO_RENOV
               - DSC_SEXO_CONDUTOR
               - FLG_PARCERIA
               - IDC_ESTADO_CIVIL_CONDUTOR
               - IDC_PROCED_VEICULO
               - FLG_VEICULO_NOVO
               - COD_PROD
               - COD_SEGMENTO_VEICULO
               - SIG_UF_PRECO

            large_categorical:
               - QTD_IDADE_CONDUTOR_MODEL
               - COD_FAMILIA_VEICULO
               - COD_REGIAO_POLITICA
               - COD_TIPO_VEICULO
               - DSC_SEGRA_ANT
               - COD_USO_VEICULO

task_model_params:
    method: dnn
    model_params:
        lr_rate_mult: 1.0
        batch_size: 128
        dropout: 0.01
        optimizer: Adam #RMSProp Nadam
        batch_norm: False
        early_stopping_it: 2
        iterations: 10
        activation: relu
        gpu: True
        regularizer: 0.01
        fb_layers: 4
        fb_initial_size: 32
        fb_min_size: 8
        fb_rate: 0.5
        sb_layers: 1
        sb_initial_size: 32
        sb_rate: 1.0
        sb_min_size: 8
        recurrent:
            type: LSTM # GRU 
            merge_type: Attention # 
            enabled: True
            num_layers: 2
            size: 16
        

    
################################################
## FLOW PARAMS
workers: 20


################################################
## GRIDSEARCH PARAMS

metric_weights: 
    w_el_err_mean: 1.0
    w_el_err_std: 0.5
    w_auc_mean: 0.1
    w_auc_std: 0.0


hyperopt_max_iterations: 10000
hyperopt_save_iterations: 5
hyperopt_load: True

# Name of the parameter to optimize and parameter path in config
params_to_opt:
    tl                : dataset_generator_params/tl
    lr_rate_mult      : task_model_params/model_params/lr_rate_mult
    batch_size        : task_model_params/model_params/batch_size
    dropout           : task_model_params/model_params/dropout
    optimizer         : task_model_params/model_params/optimizer
    batch_norm        : task_model_params/model_params/batch_norm
    iterations        : task_model_params/model_params/iterations
    activation        : task_model_params/model_params/activation
    fb_layers         : task_model_params/model_params/fb_layers
    fb_initial_size   : task_model_params/model_params/fb_initial_size
    fb_min_size       : task_model_params/model_params/fb_min_size
    fb_rate           : task_model_params/model_params/fb_rate
    sb_layers         : task_model_params/model_params/sb_layers
    sb_initial_size   : task_model_params/model_params/sb_initial_size
    sb_rate           : task_model_params/model_params/sb_rate
    sb_min_size       : task_model_params/model_params/sb_min_size
    regularizer       : task_model_params/model_params/regularizer
    

# Special Kind of parameter (features)
opt_groups: True

opt_params:
    tl:
        first: 3
        last: 6
        step: 1
        type: int_discrete
    lr_rate_mult:
        first: -1
        last: 3
        type: log_float
    batch_size:
        first: 32
        last: 512
        step: 32
        type: int_discrete
    dropout:
        first: 0.01
        last: 0.2
        type: float
    optimizer:
        values:
            - rmsprop
            - adam
            - nadam
        type: choice
    batch_norm:
        values:
            - True
            - False
        type: choice
    iterations:
        first: 1
        last: 50
        step: 2
        type: int_discrete
    activation:
        values:
            - relu
            - tanh
            - elu
            - selu
        type: choice
    fb_layers:
        first: 1
        last: 5
        step: 1
        type: int_discrete
    fb_initial_size:
        first: 8
        last: 256
        step: 16
        type: int_discrete
    fb_rate:
        first: 0.5
        last: 1.5
        step: 0.15
        type: float_discrete
    fb_min_size:
        first: 8
        last: 64
        step: 8
        type: int_discrete
    sb_layers:
        first: 0
        last: 4
        step: 1
        type: int_discrete
    sb_initial_size:
        first: 8
        last: 256
        step: 16
        type: int_discrete
    sb_rate:
        first: 0.5
        last: 1.5
        step: 0.15
        type: float_discrete
    sb_min_size:
        first: 8
        last: 64
        step: 8
        type: int_discrete
    regularizer:
        first: -5
        last: 3
        type: log_float

variable_groups:
    group1:
        - DIFERENCA_50C

    group3: 
        - VAL_PR_ANUAL_LIQUIDO_RENOV
    
    group5: 
        - VAL_LMR_CASCO
    
    group6: 
        - DSC_SEXO_CONDUTOR
    
    group7: 
        - VAL_PR_ANUAL_LIQUIDO
    
    group8: 
        - SOMA_PERIODO
    
    group10: 
        - FIDELIZACAO
    
    group11: 
        - SIG_UF_PRECO
    
    group12: 
        - FLG_CAPITAL
    
    group13:
        - SP_RENOV
        - RAZAO_C
        - IDC_ESTADO_CIVIL_CONDUTOR
        - IDC_PROCED_VEICULO        
    
    group15:
        - PCT_PERDA_CORRETOR_LAG2
        - MUDANCA_RISCO
        - FLG_VEICULO_NOVO
        - COD_PORTE_VEICULO
    
    group19:
        - COD_TIPO_VEICULO
        - DSC_SEGRA_ANT
        - QTD_SIN_PP
        
    group20:
        - COD_USO_VEICULO
        - QTD_SIN_RCF
        - SOW_LAG2

    group21: 
        - GANHO_SUM_reg_cat
        
    group25: 
        - GANHO_SUM_LAG_3_reg
        
    group26: 
        - PERDA_SUM_LAG_3_reg     
        
    group29:
        - TX_COMERCIAL_ALLIANZ
        - TX_COMERCIAL_AZUL
        - TX_COMERCIAL_BRADESCO
        - TX_COMERCIAL_HDI
        - TX_COMERCIAL_LIBERTY
        - TX_COMERCIAL_MAPFRE
        - TX_COMERCIAL_PORTO
        - TX_COMERCIAL_TOKIO
        
    group30:
        - TX_COMERCIAL_ALLIANZ_LAG_1
        - TX_COMERCIAL_AZUL_LAG_1
        - TX_COMERCIAL_BRADESCO_LAG_1
        - TX_COMERCIAL_HDI_LAG_1
        - TX_COMERCIAL_LIBERTY_LAG_1
        - TX_COMERCIAL_MAPFRE_LAG_1
        - TX_COMERCIAL_PORTO_LAG_1
        - TX_COMERCIAL_TOKIO_LAG_1
        
    group32:
        - TX_COMERCIAL_ALLIANZ_LAG_3
        - TX_COMERCIAL_AZUL_LAG_3
        - TX_COMERCIAL_BRADESCO_LAG_3
        - TX_COMERCIAL_HDI_LAG_3
        - TX_COMERCIAL_LIBERTY_LAG_3
        - TX_COMERCIAL_MAPFRE_LAG_3
        - TX_COMERCIAL_PORTO_LAG_3
        - TX_COMERCIAL_TOKIO_LAG_3
        
    group33:
        - TX_COMERCIAL_ALLIANZ_LAG_4
        - TX_COMERCIAL_AZUL_LAG_4
        - TX_COMERCIAL_BRADESCO_LAG_4
        - TX_COMERCIAL_HDI_LAG_4
        - TX_COMERCIAL_LIBERTY_LAG_4
        - TX_COMERCIAL_MAPFRE_LAG_4
        - TX_COMERCIAL_PORTO_LAG_4
        - TX_COMERCIAL_TOKIO_LAG_4
        
    group34:
        - TX_COMERCIAL_ALLIANZ_LAG_5
        - TX_COMERCIAL_AZUL_LAG_5
        - TX_COMERCIAL_BRADESCO_LAG_5
        - TX_COMERCIAL_HDI_LAG_5
        - TX_COMERCIAL_LIBERTY_LAG_5
        - TX_COMERCIAL_MAPFRE_LAG_5
        - TX_COMERCIAL_PORTO_LAG_5
        - TX_COMERCIAL_TOKIO_LAG_5
        
    group35:
        - TX_COMERCIAL_ALLIANZ_LAG_6
        - TX_COMERCIAL_AZUL_LAG_6
        - TX_COMERCIAL_BRADESCO_LAG_6
        - TX_COMERCIAL_HDI_LAG_6
        - TX_COMERCIAL_LIBERTY_LAG_6
        - TX_COMERCIAL_MAPFRE_LAG_6
        - TX_COMERCIAL_PORTO_LAG_6
        - TX_COMERCIAL_TOKIO_LAG_6
        
    group36:
        - SCORE_PREMIO
    group37:
        - SCORE_COMISSAO
    group38:
        - SCORE_RISCO
    group39:
        - SCORE_TEMPORAL
    group40:
        - SCORE_CAPTACAO_RNV_SAS
    group41:
        - SCORE_CAPTACAO_TOTAL
    group42:
        - SCORE_TAMANHO
    group43:
        - SCORE_CAPTACAO_VN
    group44:
        - SCORE_MARGEM
    group45:
        - IC
    group46:
        - IC_LAG_1
    group47:
        - IC_LAG_2
    group48:
        - IC_LAG_3