################################################
## STORAGE DIRECTORY 

base_dir: gs://marketprice/renov/bain/sp5/ds/
ds_name: flow_test
base_dir_predict: gs://marketprice/renov/bain/sp5/predict/
model_name: flow_test

run_dir: /data/
report_id: first_test

################################################
## BACKTEST PARAMS

initial_training_month: 1-7-2018
last_predicting_month:  31-7-2019 

save_experiment: False

################################################
## ELASTICITY PARAMS

elasticity_periods: 201908


################################################
## FEATURE PARAMS

original_params:
    date_col: DAT_FIM_VIGENCIA_GERAL
    target: QTD_PROP
    hash_col: key

params:  
    date_col: DATE
    target: TARGET
    model_output: PREDICTED

analysis_variables:  
    - KEY
    - COD_CAT_TARIFA_BAS
    - COD_TIPO_RENOV
    - NME_REGIONAL_PRECO
    - VAL_PR_ANUAL_LIQUIDO_RENOV
    - VAL_PR_ANUAL_LIQUIDO
    
elasticity_variables: TESTE

label: QTD_PROP

feature_label: all_features + label

vehicle_categ: 10, 11, 14, 15, 20, 21
dataset_filter: WHERE  COD_CAT_TARIFA_BAS in (10, 11, 14, 15, 20, 21)
table_name: sas-auto-marketprice-analytics.MKT_PRICING.MKT_PRICING_RENOV_201807_20191023_UPDFEAT_MODEL


################################################
## PIPELINE PARAMS

dataset_generator_params:
    all_features: 
        - FIDELIZACAO
        - VAL_LMR_CASCO
        - SCORE_CAPTACAO_VN
        - SCORE_CAPTACAO_TOTAL
        - VAL_PR_ANUAL_LIQUIDO_RENOV
        - PERDA_SUM_LAG_3_reg
        - GANHO_SUM_reg_cat
        - COD_CLASSE_BONUS
        - PCT_PERDA_CORRETOR_LAG3
        - COD_FAMILIA_VEICULO
        - FLG_VEICULO_NOVO
        - COD_PORTE_VEICULO
        - SP_INICIAL
        - IDC_ESTADO_CIVIL_CONDUTOR
        - IDC_PROCED_VEICULO
        - SIG_UF_PRECO
        - DSC_SEXO_CONDUTOR
        - VAL_PR_ANUAL_LIQUIDO
        
    tl: 1          # Train Lenght
    tl_mode: m
    ld: 1          # Lead Time
    ld_mode: m
    testl: 3       # Test Length
    testl_mode: m
    sl: 1         # Stride Length
    sl_mode: m
    
    method: gcp_bq

task_engineer_params:
    methods: 
        one_hot_mean_enc:
            small_categorical: 
               - IDC_AVAL_RISCO
               - MUDANCA_RISCO
               - COD_CLASSE_BONUS
               - COD_CAT_TARIFA_BAS
               - FLG_CAPITAL
               - NME_REGIONAL_PRECO
               - DSC_RESID_JOVEM_PART
               - COD_PORTE_VEICULO
               - FIDELIZACAO
               - COD_TIPO_RENOV
               - DSC_SEXO_CONDUTOR
               - FLG_PARCERIA
               - IDC_ESTADO_CIVIL_CONDUTOR
               - IDC_PROCED_VEICULO
               - FLG_VEICULO_NOVO
               - COD_PROD
               - COD_SEGMENTO_VEICULO
               - SIG_UF_PRECO

            large_categorical:
               - QTD_IDADE_CONDUTOR_MODEL
               - COD_FAMILIA_VEICULO
               - COD_REGIAO_POLITICA
               - COD_TIPO_VEICULO
               - DSC_SEGRA_ANT
               - COD_USO_VEICULO

task_model_params:
    method: dnn_pt
    model_params:
        log_interval: 500
        lr_rate_mult: 1.0
        batch_size: 128
        dropout: 0.01
        optimizer: Adam #RMSProp Nadam
        batch_norm: False
        early_stopping_it: 2
        iterations: 10
        activation: relu
        gpu: True
        regularizer: 0.01
        fb_layers: 4
        fb_initial_size: 32
        fb_min_size: 8
        fb_rate: 0.5
        sb_layers: 1
        sb_initial_size: 32
        sb_rate: 1.0
        sb_min_size: 8
        recurrent:
            type: LSTM # GRU 
            merge_type: Attention # 
            enabled: True
            num_layers: 2
            size: 16
        

    
################################################
## FLOW PARAMS
workers: 10
